### ISSUE TITLE
copy paste my repo?

### ISSUE THREAD

**Issue by MichaelHorsch** [Gobiner/ImageResizer.Sitecore.old#1]
Hey dude, 

This seems very similar to my plugin that I made in 2014.  Even some of the comments are identical.  https://github.com/MichaelHorsch/ImageResizer.Sitecore.Plugin

You should fork it and add your changes.

**Comment by Gobiner** [comment]
Ok done. https://github.com/Gobiner/ImageResizer.Sitecore
